### ISSUE TITLE
Gather API keys for transit feeds that require them

### ISSUE THREAD

**Issue by barbeau** [CUTR-at-USF/transit-feed-quality-calculator#29]
**Summary:** 

From https://github.com/CUTR-at-USF/transit-feed-quality-calculator/issues/8, which implemented the `CsvDownloader`:

A note for our internal processing tools - we need to compile API keys for the following transit agencies and add them to our CSV file (or otherwise figure out why they aren't working). See below for list from #8):

**List of feeds from TransitFeeds.com we need API keys for, along with dev website URL**

- [x] BART Trip Updates - https://www.bart.gov/schedules/developers/gtfs-realtime
- [x] BART Alerts - https://www.bart.gov/schedules/developers/gtfs-realtime
- [x] VIA TU, VP, Service Alerts - http://www.viainfo.net/developers-resources/
- [ ] Metra Trip Updates - https://metrarail.com/developers (Requested API key via online form on Feb 7, 2018.  Got key on Feb 13, not sure what to do with it - I emailed to ask.  Turns out this requires HTTP basic authentication, which I've ticketed in https://github.com/CUTR-at-USF/transit-feed-quality-calculator/issues/31.)
- [ ] Metra Vehicle Positions - https://metrarail.com/developers (Requested API key via online form on Feb 7, 2018.  Got key on Feb 13, not sure what to do with it - I emailed to ask.  Turns out this requires HTTP basic authentication, which I've ticketed in https://github.com/CUTR-at-USF/transit-feed-quality-calculator/issues/31.)
- [ ] Metra Service Alerts - https://metrarail.com/developers (Requested API key via online form on Feb 7, 2018.  Got key on Feb 13, not sure what to do with it - I emailed to ask.  Turns out this requires HTTP basic authentication, which I've ticketed in https://github.com/CUTR-at-USF/transit-feed-quality-calculator/issues/31.)
~~- [ ] NJ Transit GTFS-realtime - http://www.njtransit.com/developers~~ As of Feb 7, 2018 doesn't appear to have a GTFS-realtime feed
- [ ] Auckland Transport Trip Updates - https://api.at.govt.nz (I submitted an application registration on Feb 7, 2018.  From an initial look, it doesn't seem like they have a GTFS zip file or protobuf GTFS-realtime messages.  Instead, there are individual REST APIs that you can get JSON responses from)
- [ ] Auckland Transport Vehicle Locations - https://api.at.govt.nz  (I submitted an application registration on Feb 7, 2018.  From an initial look, it doesn't seem like they have a GTFS zip file or protobuf GTFS-realtime messages.  Instead, there are individual REST APIs that you can get JSON responses from)
- [x] AC Transit Vehicle Positions - http://api.actransit.org/transit/
- [x] AC Transit Service Alerts - http://api.actransit.org/transit/
- [x] AC Transit Trip Updates - http://api.actransit.org/transit/
- [x] Capital Metro Service Alerts - https://www.capmetro.org/metrolabs/
- [x] Capital Metro Vehicle Positions - https://www.capmetro.org/metrolabs/
- [x] Capital Metro Trip Updates - https://www.capmetro.org/metrolabs/
- [ ] Sound Transit Vehicle Positions - http://www.soundtransit.org/Developer-resources/Data-downloads
- [ ] Sound Transit Trip Updates - http://www.soundtransit.org/Developer-resources/Data-downloads
- [ ] Intercity Transit Vehicle Positions - http://www.soundtransit.org/Developer-resources/Data-downloads
- [ ] Intercity Transit Trip Updates - http://www.soundtransit.org/Developer-resources/Data-downloads
- [ ] Pierce Transit Vehicle Positions - http://www.soundtransit.org/Developer-resources/Data-downloads
- [ ] Pierce Transit Trip Updates - http://www.soundtransit.org/Developer-resources/Data-downloads
- [ ] KCM Vehicle Positions - http://www.soundtransit.org/Developer-resources/Data-downloads
- [ ] KCM Trip Updates - http://www.soundtransit.org/Developer-resources/Data-downloads
- [ ] Long Island Rail Road Trip Updates - http://datamine.mta.info
- [ ] Metro-North Railroad Trip Updates - http://datamine.mta.info
- [ ] NYC Subway Real-Time Estimates (Staten Island Railway) - http://datamine.mta.info/
- [ ] NYC Subway Real-Time Estimates (L Train) - http://datamine.mta.info/
- [ ] NYC Subway Real-Time Estimates - http://datamine.mta.info/
- [x] TriMet Trip Updates - http://developer.trimet.org/GTFS.shtml
- [x] TriMet Alerts - http://developer.trimet.org/GTFS.shtml
- [ ] AMT Vehicle Positions - http://amt.qc.ca/developers/
- [ ] AMT Alerts - http://amt.qc.ca/developers/
- [ ] AMT Trip Updates - http://amt.qc.ca/developers/
- [ ] TransLink SEQ Vehicle Positions & Trip Updates - https://gtfsrt.api.translink.com.au/

We may also need to include Denver RTD as well - here's the error message we're currently getting for those URLs:
~~~
Error reading GTFS-realtime feed 'http://www.rtd-denver.com/google_sync/VehiclePosition.pb' - java.io.IOException: Server returned HTTP response code: 401 for URL: http://www.rtd-denver.com/google_sync/VehiclePosition.pb
Error reading GTFS-realtime feed 'http://www.rtd-denver.com/google_sync/TripUpdate.pb' - java.io.IOException: Server returned HTTP response code: 401 for URL: http://www.rtd-denver.com/google_sync/TripUpdate.pb
~~~

**Steps to reproduce:** 

Run the tool using both the TransitFeeds.com API and our CSV file

**Expected behavior:** 

Download feeds successfully from the above URLs (e.g., if they require API keys, add them to our `CsvDownloader`)

**Observed behavior:** 

We can't automatically process these feeds from the TransitFeeds.com API

**Platform:** 

Windows 7 Enterprise SP1 with Java 64bit 9.0.1

**Comment by barbeau** [comment]
I just ran this again against TransitFeeds.com, and here's the current log output for fetching feeds that I haven't already listed above - note that it appears some of them have broken URLs coming from TransitFeeds.com:

~~~
Error downloading GTFS-realtime feed 'http://feed.ltd.org/gtfs-realtime/alerts' - java.io.FileNotFoundException: http://feed.ltd.org/gtfs-realtime/alerts
Error downloading GTFS-realtime feed 'http://kingston.metrolinx.tmix.se/gtfs-realtime/vehicleupdates.pb' - java.net.ConnectException: Connection timed out: connect
Error downloading GTFS-realtime feed 'http://kingston.metrolinx.tmix.se/gtfs-realtime/tripupdates.pb' - java.net.ConnectException: Connection timed out: connect
Error downloading GTFS-realtime feed 'http://kingston.metrolinx.tmix.se/gtfs-realtime/alerts.pb' - java.net.ConnectException: Connection timed out: connect
Error downloading GTFS-realtime feed 'http://transitdata.calgary.ca/ctransit/alerts.pb' - java.io.FileNotFoundException: http://transitdata.calgary.ca/ctransit/alerts.pb
Error downloading GTFS-realtime feed 'http://transitdata.calgary.ca/ctransit/tripupdates.pb' - java.io.FileNotFoundException: http://transitdata.calgary.ca/ctransit/tripupdates.pb
Error downloading GTFS-realtime feed 'http://transitdata.calgary.ca/ctransit/vehiclepositions.pb' - java.io.IOException: Server returned HTTP response code: 403 for URL: http://transitdata.calgary.ca/ctransit/vehiclepositions.pb
Error downloading GTFS-realtime feed 'https://gtfsrt.api.translink.com.au/Feed/MCS' - java.io.FileNotFoundException: https://gtfsrt.api.translink.com.au/Feed/MCS
Error downloading GTFS-realtime feed 'http://onebusaway.gatech.edu:8080/vehicle-positions' - java.net.UnknownHostException: onebusaway.gatech.edu
Error downloading GTFS-realtime feed 'http://onebusaway.gatech.edu:8080/trip-updates' - java.net.UnknownHostException: onebusaway.gatech.edu
Error downloading GTFS feed 'http://www.riversidetransit.com/google_transit.zip' - java.io.IOException: Server returned HTTP response code: 403 for URL: https://www.riversidetransit.com/google_transit.zip
~~~
